# 每页行数  在1到5之间 正整数
height: 5
# 总页数
totalAmount: 3
# 初始给多少行默认开启的格子
initialAmount: 9
# vip背包的高度  1到6
vipHeight: 6
# 解锁格子需要的金币/点券
# 行数:金币/点券   金币直接填数值 点券数值后面加上一个d
money:
  - '10:100'   # 解锁10行需100金币
  - '11:1000'
  - '12:1000'
  - '13:1000'
  - '14:3600'
  - '15:10000d'   # 解锁15行需1w点券