itemList:
  普通力量宝珠:
    Id: 381
    Data: 0
    Name: "&c力量宝珠  &6[&a普通&6]"
    Lore:
      - '&f宝珠           普通'
      - '&3拖动此物品点击目标'
      - '&3装备进行入魂'
      - '&a+5 力量'
      - '&c*适用：&9武器,副武器'
    Type:
      - "sword"
      - "shield"
      - "bow"
      - "hat"
      - "chest"
      - "leg"
      - "bot"
      - ""
    addLore:
      - '&8&m==========&8[&d 附魔&8 ]&8&m=========='
      - '&7附魔：&c力量宝珠 &8[&f普通&8]'
      - '&7力量: &c+5'
    Identify: '&8&m==========&8[&d 附魔&8 ]&8&m=========='